### ISSUE TITLE
Deployment issues

### ISSUE THREAD

**Issue by itsjpavank** [Azure-Samples/media-services-v3-dotnet-core-functions-integration#3]
{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"NotFound","message":"{\r\n \"Code\": \"NotFound\",\r\n \"Message\": \"Cannot find SourceControlToken with name GitHub.\",\r\n \"Target\": null,\r\n \"Details\": [\r\n {\r\n \"Message\": \"Cannot find SourceControlToken with name GitHub.\"\r\n },\r\n {\r\n \"Code\": \"NotFound\"\r\n },\r\n {\r\n \"ErrorEntity\": {\r\n \"ExtendedCode\": \"51004\",\r\n \"MessageTemplate\": \"Cannot find {0} with name {1}.\",\r\n \"Parameters\": [\r\n \"SourceControlToken\",\r\n \"GitHub\"\r\n ],\r\n \"Code\": \"NotFound\",\r\n \"Message\": \"Cannot find SourceControlToken with name GitHub.\"\r\n }\r\n }\r\n ],\r\n \"Innererror\": null\r\n}"}]}

**Comment by xpouyat** [comment]
Hi,
This may be the issue documented in readme.md : 

Note : if you never provided your GitHub account in the Azure portal before, the continuous integration probably will probably fail and you won't see the functions. In that case, you need to setup it manually. Go to your azure functions deployment / Functions app settings / Configure continous integration. Select GitHub as a source and configure it to use your fork.

**Comment by itsjpavank** [comment]
My bad, forgot to provide the link of repo
