### ISSUE TITLE
Deploy Error

### ISSUE THREAD

**Issue by rodrigoctoledo** [Azure-Samples/media-services-v3-dotnet-core-functions-integration#4]
Hello,
I'm trying to deploy the application by passing the parameters, when I do, it returns this error:

![image](https://user-images.githubusercontent.com/29310960/75694872-fa6cdc00-5c87-11ea-8a03-b7d45190cb13.png)

{
    "Code": "NotFound",
    "Message": "Cannot find SourceControlToken with name GitHub.",
    "Target": null,
    "Details": [
        {
            "Message": "Cannot find SourceControlToken with name GitHub."
        },
        {
            "Code": "NotFound"
        },
        {
            "ErrorEntity": {
                "ExtendedCode": "51004",
                "MessageTemplate": "Cannot find {0} with name {1}.",
                "Parameters": [
                    "SourceControlToken",
                    "GitHub"
                ],
                "Code": "NotFound",
                "Message": "Cannot find SourceControlToken with name GitHub."
            }
        }
    ],
    "Innererror": null
}

As it is not found, I cannot trace the cause
can help?

thankful

**Comment by xpouyat** [comment]
You need to manually connect the function app to your GitHub (using the portal). This happens the first time. This is documented in the step by step guide.
