### ISSUE TITLE
Logic app

### ISSUE THREAD

**Issue by rodrigoctoledo** [Azure-Samples/media-services-v3-dotnet-core-functions-integration#6]
hi, I just need to do the VOD process, and I deployed the function but I think it's from another project, can you guide me?
Error:
![image](https://user-images.githubusercontent.com/29310960/75996323-7b241600-5edc-11ea-9711-02d1572df9d5.png)

Custom Deployment: 
![image](https://user-images.githubusercontent.com/29310960/75996389-9000a980-5edc-11ea-8a96-abb8b73229f6.png)

location where I uploaded:
![image](https://user-images.githubusercontent.com/29310960/75996534-bfafb180-5edc-11ea-8efb-44c0d9c1c610.png)

is correct ?

thankful
Rodrigo Toledo

**Comment by xpouyat** [comment]
You need to deploy the functions (for AMS v3), make sure the functions are working, then you can deploy the logic app. I am not sure the logic app template is fully operational. You may need to tweak it.

**Comment by rodrigoctoledo** [comment]
Hi, 
this ? 

https://github.com/Azure-Samples/media-services-v3-dotnet-core-functions-integration/tree/master/advanced-vod-workflow

![image](https://user-images.githubusercontent.com/29310960/76010182-41a9d580-5ef1-11ea-842d-13f863115616.png)

**Comment by xpouyat** [comment]
Yes, you need to deploy these functions. Open the Visual Studio Solution LiveAndVodDRMOperationsV3.sln locally, and publish the functions to Azure using Publish feature on the project (right click on the project).
